using System.Text.Json.Serialization;
using Ai.Tlbx.MidTerm.Api.Models;
using Ai.Tlbx.MidTerm.Models;
using Ai.Tlbx.MidTerm.Models.Auth;
using Ai.Tlbx.MidTerm.Models.Certificates;
using Ai.Tlbx.MidTerm.Models.Files;
using Ai.Tlbx.MidTerm.Models.History;
using Ai.Tlbx.MidTerm.Models.Sessions;
using Ai.Tlbx.MidTerm.Models.Share;
using Ai.Tlbx.MidTerm.Models.Security;
using Ai.Tlbx.MidTerm.Models.System;
using Ai.Tlbx.MidTerm.Models.Update;
using Ai.Tlbx.MidTerm.Settings;
using Ai.Tlbx.MidTerm.Common.Logging;
using Microsoft.AspNetCore.Mvc;

namespace Ai.Tlbx.MidTerm.Api;

[JsonSerializable(typeof(BootstrapResponse))]
[JsonSerializable(typeof(BootstrapLoginResponse))]
[JsonSerializable(typeof(FeatureFlags))]
[JsonSerializable(typeof(WsCommand))]
[JsonSerializable(typeof(WsCommandPayload))]
[JsonSerializable(typeof(WsCommandResponse))]
[JsonSerializable(typeof(WsSessionCreatedData))]
[JsonSerializable(typeof(SystemResponse))]
[JsonSerializable(typeof(TtyHostInfo))]
[JsonSerializable(typeof(HistoryPatchRequest))]
[JsonSerializable(typeof(HistoryReorderRequest))]
[JsonSerializable(typeof(LogSeverity))]
[JsonSerializable(typeof(ProblemDetails))]
[JsonSerializable(typeof(SessionListDto))]
[JsonSerializable(typeof(SessionInfoDto))]
[JsonSerializable(typeof(SessionSupervisorInfoDto))]
[JsonSerializable(typeof(SessionAttentionResponse))]
[JsonSerializable(typeof(SessionAttentionItem))]
[JsonSerializable(typeof(List<SessionAttentionItem>))]
[JsonSerializable(typeof(CreateSessionRequest))]
[JsonSerializable(typeof(WorkerBootstrapRequest))]
[JsonSerializable(typeof(WorkerBootstrapResponse))]
[JsonSerializable(typeof(RenameSessionRequest))]
[JsonSerializable(typeof(SetSessionNotesRequest))]
[JsonSerializable(typeof(SetSessionTopicRequest))]
[JsonSerializable(typeof(SetSessionControlRequest))]
[JsonSerializable(typeof(ResizeRequest))]
[JsonSerializable(typeof(ResizeResponse))]
[JsonSerializable(typeof(FileUploadResponse))]
[JsonSerializable(typeof(List<NetworkInterfaceDto>))]
[JsonSerializable(typeof(ShellInfoDto))]
[JsonSerializable(typeof(List<ShellInfoDto>))]
[JsonSerializable(typeof(MidTermSettingsPublic))]
[JsonSerializable(typeof(TerminalColorSchemeDefinition))]
[JsonSerializable(typeof(List<TerminalColorSchemeDefinition>))]
[JsonSerializable(typeof(UpdateInfo))]
[JsonSerializable(typeof(LocalUpdateInfo))]
[JsonSerializable(typeof(UpdateType))]
[JsonSerializable(typeof(UpdateResult))]
[JsonSerializable(typeof(VersionManifest))]
[JsonSerializable(typeof(StateUpdate))]
[JsonSerializable(typeof(SessionLayoutState))]
[JsonSerializable(typeof(LayoutNode))]
[JsonSerializable(typeof(List<LayoutNode>))]
[JsonSerializable(typeof(SystemHealth))]
[JsonSerializable(typeof(UserInfo))]
[JsonSerializable(typeof(List<UserInfo>))]
[JsonSerializable(typeof(LoginRequest))]
[JsonSerializable(typeof(ChangePasswordRequest))]
[JsonSerializable(typeof(AuthResponse))]
[JsonSerializable(typeof(AuthStatusResponse))]
[JsonSerializable(typeof(CertificateInfoResponse))]
[JsonSerializable(typeof(CertificateDownloadInfo))]
[JsonSerializable(typeof(SecurityStatus))]
[JsonSerializable(typeof(ApiKeyInfoResponse))]
[JsonSerializable(typeof(List<ApiKeyInfoResponse>))]
[JsonSerializable(typeof(ApiKeyListResponse))]
[JsonSerializable(typeof(CreateApiKeyRequest))]
[JsonSerializable(typeof(CreateApiKeyResponse))]
[JsonSerializable(typeof(FirewallRuleStatusResponse))]
[JsonSerializable(typeof(SharePacketInfo))]
[JsonSerializable(typeof(NetworkEndpointInfo))]
[JsonSerializable(typeof(NetworkEndpointInfo[]))]
[JsonSerializable(typeof(CreateShareLinkRequest))]
[JsonSerializable(typeof(CreateShareLinkResponse))]
[JsonSerializable(typeof(ActiveShareGrantInfo))]
[JsonSerializable(typeof(List<ActiveShareGrantInfo>))]
[JsonSerializable(typeof(ActiveShareGrantListResponse))]
[JsonSerializable(typeof(ClaimShareRequest))]
[JsonSerializable(typeof(ClaimShareResponse))]
[JsonSerializable(typeof(ShareBootstrapResponse))]
[JsonSerializable(typeof(ShareAccessMode))]
[JsonSerializable(typeof(CursorStyleSetting))]
[JsonSerializable(typeof(ThemeSetting))]
[JsonSerializable(typeof(BellStyleSetting))]
[JsonSerializable(typeof(ClipboardShortcutsSetting))]
[JsonSerializable(typeof(TabTitleModeSetting))]
[JsonSerializable(typeof(LogSubscribeMessage))]
[JsonSerializable(typeof(LogEntryMessage))]
[JsonSerializable(typeof(LogHistoryMessage))]
[JsonSerializable(typeof(LogSessionsMessage))]
[JsonSerializable(typeof(LogSessionInfo))]
[JsonSerializable(typeof(List<LogSessionInfo>))]
[JsonSerializable(typeof(List<LogEntryMessage>))]
[JsonSerializable(typeof(LogFilesResponse))]
[JsonSerializable(typeof(LogFileInfo))]
[JsonSerializable(typeof(List<LogFileInfo>))]
[JsonSerializable(typeof(LogReadResponse))]
[JsonSerializable(typeof(SettingsWsMessage))]
[JsonSerializable(typeof(LaunchEntry))]
[JsonSerializable(typeof(List<LaunchEntry>))]
[JsonSerializable(typeof(CreateHistoryRequest))]
[JsonSerializable(typeof(SetBookmarkRequest))]
[JsonSerializable(typeof(FileCheckRequest))]
[JsonSerializable(typeof(FileCheckResponse))]
[JsonSerializable(typeof(FileRegisterRequest))]
[JsonSerializable(typeof(FileResolveResponse))]
[JsonSerializable(typeof(FilePathInfo))]
[JsonSerializable(typeof(DirectoryListResponse))]
[JsonSerializable(typeof(DirectoryEntry))]
[JsonSerializable(typeof(Dictionary<string, FilePathInfo>))]
[JsonSerializable(typeof(FileSaveRequest))]
[JsonSerializable(typeof(FileSaveResponse))]
[JsonSerializable(typeof(PathsResponse))]
[JsonSerializable(typeof(ManagerBarButton))]
[JsonSerializable(typeof(List<ManagerBarButton>))]
[JsonSerializable(typeof(ManagerBarTrigger))]
[JsonSerializable(typeof(ManagerBarScheduleEntry))]
[JsonSerializable(typeof(List<ManagerBarScheduleEntry>))]
[JsonSourceGenerationOptions(PropertyNamingPolicy = JsonKnownNamingPolicy.CamelCase, UseStringEnumConverter = true)]
public partial class AppJsonContext : JsonSerializerContext
{
}
