using System.Diagnostics;
using System.Text.Json;
using Ai.Tlbx.MidTerm.Services;
using Ai.Tlbx.MidTerm.Services.Browser;
using Microsoft.AspNetCore.Builder;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Xunit;

namespace Ai.Tlbx.MidTerm.UnitTests;

[Collection(PathSensitiveEnvironmentCollection.Name)]
public sealed class TlbxCliScriptWriterTests : IDisposable
{
    private readonly string _tempDir = Path.Combine(Path.GetTempPath(), "tlbx-cli-tests", Guid.NewGuid().ToString("N"));

    [Theory]
    [InlineData(false, "")]
    [InlineData(false, "deadbeef")]
    [InlineData(true, "")]
    [InlineData(true, "deadbeef")]
    public async Task LiveProcessContextRepairsMissingOrStaleIdentityBeforeFirstMutation(bool bash, string inheritedId)
    {
        if ((bash ? ResolveBashPath() : ResolvePowerShellPath()) is null) return;
        Directory.CreateDirectory(_tempDir);
        TlbxCliScriptWriter.WriteScripts(_tempDir, 2100, "test-token");
        var builder = WebApplication.CreateSlimBuilder();
        builder.WebHost.UseUrls("http://127.0.0.1:0");
        await using var app = builder.Build();
        var requests = new System.Collections.Concurrent.ConcurrentQueue<string>();
        app.MapGet("/api/sessions/process-context", (int processId) =>
        {
            using var process = Process.GetProcessById(processId);
            requests.Enqueue("resolve");
            return Results.Text("abcdefgh");
        });
        app.MapPost("/api/git/repos", async (HttpContext context) =>
        {
            using var body = await JsonDocument.ParseAsync(context.Request.Body, cancellationToken: context.RequestAborted);
            requests.Enqueue(body.RootElement.GetProperty("sessionId").GetString()!);
            return Results.Ok();
        });
        app.MapGet("/api/git/repos", (string sessionId) =>
        {
            requests.Enqueue(sessionId);
            return Results.Ok();
        });
        await app.StartAsync(CancellationToken.None);
        var result = await RunContextShellAsync(bash,
            bash ? "source \"$1\"; set -e; mt_repo add '/repo'; mt_repo --session sibling1 list; test \"$MT_SESSION_ID\" = abcdefgh"
                : ". $args[0]; mt_repo add '/repo'; mt_repo list -SessionId sibling1; if ($env:MT_SESSION_ID -ne 'abcdefgh') { throw 'Wrong identity' }",
            app.Urls.Single(), inheritedId, Path.Combine(_tempDir, bash ? "tlbx_cli.sh" : "tlbx_cli.ps1"));
        Assert.True(result.ExitCode == 0, result.Error + result.Output);
        Assert.Equal(new[] { "resolve", "abcdefgh", "sibling1" }, requests.ToArray());
    }

    [Theory]
    [InlineData(false, false)]
    [InlineData(false, true)]
    [InlineData(true, false)]
    [InlineData(true, true)]
    public async Task ContextExport_KeepsGitRequestsOnOwningServerAcrossShells(bool producerBash, bool consumerBash)
    {
        if (ResolveBashPath() is null || ResolvePowerShellPath() is null) return;

        Directory.CreateDirectory(_tempDir);
        TlbxCliScriptWriter.WriteScripts(_tempDir, 2100, "test-token");
        var builder = WebApplication.CreateSlimBuilder();
        builder.WebHost.UseUrls("http://127.0.0.1:0");
        await using var app = builder.Build();
        app.MapGet("/{instance}/api/git/repos", (string instance, string sessionId) =>
            instance == "owner" && sessionId == "abcdefgh"
                ? Results.Json(new { sessionId })
                : Results.NotFound("Session not found"));
        await app.StartAsync(CancellationToken.None);
        var server = app.Urls.Single();
        var exports = await RunContextShellAsync(producerBash,
            producerBash ? "source \"$1\"; mt_context \"$2\"" : ". $args[0]; mt_context $args[1]",
            server + "/owner", "abcdefgh",
            Path.Combine(_tempDir, producerBash ? "tlbx_cli.sh" : "tlbx_cli.ps1"),
            consumerBash ? "--bash" : "--pwsh");
        Assert.Equal(0, exports.ExitCode);
        Assert.DoesNotContain("test-token", exports.Output, StringComparison.Ordinal);
        var exportPath = Path.Combine(_tempDir, consumerBash ? "context.sh" : "context.ps1");
        await File.WriteAllTextAsync(exportPath, exports.Output, CancellationToken.None);

        // A daemon/remote shell may inherit another instance's environment and
        // load a helper generated by that instance. The exported tuple must win.
        var result = await RunContextShellAsync(consumerBash,
            consumerBash ? "source \"$1\"; source \"$2\"; mt_repo list" : ". $args[0]; . $args[1]; mt_repo list",
            server + "/other", "deadbeef", exportPath,
            Path.Combine(_tempDir, consumerBash ? "tlbx_cli.sh" : "tlbx_cli.ps1"));
        Assert.True(result.ExitCode == 0, result.Error + result.Output);
        using var json = JsonDocument.Parse(result.Output);
        Assert.Equal("abcdefgh", json.RootElement.GetProperty("sessionId").GetString());
    }

    [Theory]
    [InlineData(false)]
    [InlineData(true)]
    public async Task Repo_ExplicitSessionOverridesStaleContextWithoutRetargetingOrRetryingFailures(bool bash)
    {
        if ((bash ? ResolveBashPath() : ResolvePowerShellPath()) is null) return;
        Directory.CreateDirectory(_tempDir);
        TlbxCliScriptWriter.WriteScripts(_tempDir, 2100, "test-token");
        var builder = WebApplication.CreateSlimBuilder();
        builder.WebHost.UseUrls("http://127.0.0.1:0");
        await using var app = builder.Build();
        var requests = new System.Collections.Concurrent.ConcurrentQueue<string>();
        app.MapMethods("/api/git/{**path}", ["GET", "POST", "DELETE"], async (HttpContext context) =>
        {
            var sessionId = context.Request.Query["sessionId"].ToString();
            if (context.Request.Method == "POST")
            {
                using var body = await JsonDocument.ParseAsync(context.Request.Body, cancellationToken: context.RequestAborted);
                sessionId = body.RootElement.GetProperty("sessionId").GetString()!;
            }
            requests.Enqueue(sessionId);
            return sessionId == "abcdefgh" ? Results.Ok() : Results.NotFound("Session not found");
        });
        await app.StartAsync(CancellationToken.None);
        var server = app.Urls.Single();
        var helper = Path.Combine(_tempDir, bash ? "tlbx_cli.sh" : "tlbx_cli.ps1");
        var result = await RunContextShellAsync(bash,
            bash
                ? "source \"$1\"; set -e; mt_repo --session abcdefgh add '/repo with space'; mt_repo --session abcdefgh refresh; mt_repo --session abcdefgh remove '/repo with space'; mt_repo --session abcdefgh list; test \"$MT_SESSION_ID\" = deadbeef"
                : ". $args[0]; mt_repo add '/repo with space' -SessionId abcdefgh; mt_repo refresh -SessionId abcdefgh; mt_repo remove '/repo with space' -SessionId abcdefgh; mt_repo list -SessionId abcdefgh; if ($env:MT_SESSION_ID -ne 'deadbeef') { throw 'Environment changed' }",
            server, "deadbeef", helper);
        Assert.True(result.ExitCode == 0, result.Error + result.Output);
        Assert.Equal(4, requests.Count);
        Assert.All(requests, id => Assert.Equal("abcdefgh", id));

        result = await RunContextShellAsync(bash,
            bash ? "source \"$1\"; mt_repo --session abcdefgh list" : ". $args[0]; mt_repo list -SessionId abcdefgh",
            server, "", helper);
        Assert.True(result.ExitCode == 0, result.Error + result.Output);
        Assert.Equal(5, requests.Count);

        result = await RunContextShellAsync(bash,
            bash ? "source \"$1\"; mt_repo add '/repo with space'" : ". $args[0]; mt_repo add '/repo with space'",
            server, "deadbeef", helper);
        Assert.NotEqual(0, result.ExitCode);
        Assert.Contains("deadbeef", result.Error, StringComparison.Ordinal);
        Assert.Contains(server, result.Error, StringComparison.Ordinal);
        Assert.Contains("mt_sessions", result.Error, StringComparison.Ordinal);
        Assert.Equal(6, requests.Count); // A mutation failure is never replayed against another session.
    }

    [Theory]
    [InlineData(false, false)]
    [InlineData(true, false)]
    [InlineData(false, true)]
    [InlineData(true, true)]
    public async Task CodexRequiresFullIdentityAndLeaseBeforeMutation(bool bash, bool bound)
    {
        if ((bash ? ResolveBashPath() : ResolvePowerShellPath()) is null) return;
        Directory.CreateDirectory(_tempDir);
        TlbxCliScriptWriter.WriteScripts(_tempDir, 2100, "test-token");
        var builder = WebApplication.CreateSlimBuilder();
        builder.WebHost.UseUrls("http://127.0.0.1:0");
        await using var app = builder.Build();
        const string identity = "01a10b30-4385-71e0-8a60-6fd26e1cfb01";
        const string lease = "0123456789abcdef0123456789abcdef";
        var mutations = new System.Collections.Concurrent.ConcurrentQueue<string>();
        app.MapGet("/api/sessions/process-context", (HttpContext context, int processId, string codexSessionId, string codexThreadId, string codexHome) =>
        {
            Assert.Equal(identity, codexSessionId);
            Assert.Equal(identity, codexThreadId);
            Assert.True(Path.IsPathFullyQualified(codexHome), codexHome);
            using var caller = Process.GetProcessById(processId);
            return Results.Text(bound ? "abcdefgh:" + lease : "TLBXCTX:" + lease + "\nTLBX_CONTEXT_UNBOUND: No session operation was executed.\nRetry the original command in a separate shell tool call.", statusCode: bound ? 200 : 409);
        });
        app.MapPost("/api/git/repos", async (HttpContext context) =>
        {
            Assert.Equal(lease, context.Request.Headers["X-Tlbx-Cli-Context"].ToString());
            using var body = await JsonDocument.ParseAsync(context.Request.Body, cancellationToken: context.RequestAborted);
            mutations.Enqueue(body.RootElement.GetProperty("sessionId").GetString()!);
            return Results.Ok();
        });
        await app.StartAsync(CancellationToken.None);
        var command = bash
            ? $"set -e; export CODEX_SESSION_ID={identity} CODEX_THREAD_ID={identity}; source \"$1\"; mt_repo add '/repo'"
            : $"$env:CODEX_SESSION_ID='{identity}'; $env:CODEX_THREAD_ID='{identity}'; . $args[0]; mt_repo add '/repo'";
        var result = await RunContextShellAsync(bash, command, app.Urls.Single(), "deadbeef", Path.Combine(_tempDir, bash ? "tlbx_cli.sh" : "tlbx_cli.ps1"));
        if (bound)
        {
            Assert.True(result.ExitCode == 0, result.Error + result.Output);
            Assert.Equal(new[] { "abcdefgh" }, mutations.ToArray());
        }
        else
        {
            Assert.NotEqual(0, result.ExitCode);
            Assert.Empty(mutations);
            Assert.Contains("TLBXCTX:" + lease, result.Output + result.Error, StringComparison.Ordinal);
            Assert.Contains("Retry the original command", result.Output + result.Error, StringComparison.Ordinal);
        }
    }

    [Theory]
    [InlineData(false)]
    [InlineData(true)]
    public async Task CodexDoesNotUseLegacyPlainIdOrBypassFailureWithExplicitTarget(bool bash)
    {
        if ((bash ? ResolveBashPath() : ResolvePowerShellPath()) is null) return;
        Directory.CreateDirectory(_tempDir);
        TlbxCliScriptWriter.WriteScripts(_tempDir, 2100, "test-token");
        var builder = WebApplication.CreateSlimBuilder();
        builder.WebHost.UseUrls("http://127.0.0.1:0");
        await using var app = builder.Build();
        var requests = new System.Collections.Concurrent.ConcurrentQueue<string>();
        app.MapGet("/api/sessions/process-context", () => Results.Text("deadbeef"));
        app.MapMethods("/api/git/{**path}", ["GET", "POST"], (HttpContext context) => { requests.Enqueue(context.Request.Path); return Results.Ok(); });
        app.MapGet("/api/sessions", () => Results.Text("global-list-ok"));
        await app.StartAsync(CancellationToken.None);
        var command = bash
            ? "set -e; export CODEX_SESSION_ID=01a10b30-4385-71e0-8a60-6fd26e1cfb01; source \"$1\"; mt_sessions; mt_repo --session sibling1 list"
            : "$env:CODEX_SESSION_ID='01a10b30-4385-71e0-8a60-6fd26e1cfb01'; . $args[0]; mt_sessions; mt_repo list -SessionId sibling1";
        var result = await RunContextShellAsync(bash, command, app.Urls.Single(), "deadbeef", Path.Combine(_tempDir, bash ? "tlbx_cli.sh" : "tlbx_cli.ps1"));
        Assert.NotEqual(0, result.ExitCode);
        Assert.Empty(requests);
        Assert.Contains("global-list-ok", result.Output, StringComparison.Ordinal);
        Assert.Contains("TLBX_CONTEXT_UNAVAILABLE", result.Output + result.Error, StringComparison.Ordinal);
    }

    private async Task<(int ExitCode, string Output, string Error)> RunContextShellAsync(
        bool bash, string command, string baseUrl, string sessionId, params string[] arguments)
    {
        var start = new ProcessStartInfo(bash ? ResolveBashPath()! : ResolvePowerShellPath()!)
        {
            UseShellExecute = false,
            RedirectStandardOutput = true,
            RedirectStandardError = true,
            CreateNoWindow = true
        };
        foreach (var key in start.Environment.Keys.Where(key => key.StartsWith("MT_", StringComparison.Ordinal)).ToArray())
            start.Environment.Remove(key);
        start.Environment.Remove("CODEX_SESSION_ID");
        start.Environment.Remove("CODEX_THREAD_ID");
        start.Environment.Remove("CODEX_HOME");
        start.Environment["MT_BASE_URL"] = baseUrl;
        start.Environment["MT_SESSION_ID"] = sessionId;
        if (bash)
        {
            start.ArgumentList.Add("-c");
            start.ArgumentList.Add(command);
            start.ArgumentList.Add("context-test");
        }
        else
        {
            var driver = Path.Combine(_tempDir, Guid.NewGuid().ToString("N") + ".ps1");
            await File.WriteAllTextAsync(driver, "$ErrorActionPreference = 'Stop'\n" + command);
            start.ArgumentList.Add("-NoProfile");
            start.ArgumentList.Add("-File");
            start.ArgumentList.Add(driver);
        }
        foreach (var argument in arguments)
            start.ArgumentList.Add(bash && File.Exists(argument) ? ToBashPath(argument) : argument);
        using var process = Process.Start(start)!;
        var stdout = process.StandardOutput.ReadToEndAsync();
        var stderr = process.StandardError.ReadToEndAsync();
        using var timeout = new CancellationTokenSource(TimeSpan.FromSeconds(30));
        try
        {
            await process.WaitForExitAsync(timeout.Token);
            return (process.ExitCode, await stdout, await stderr);
        }
        finally
        {
            if (!process.HasExited) process.Kill(entireProcessTree: true);
        }
    }

    [Fact]
    public void SourceInstance_PreservesSupervisorHelpersAndKeepsItsOwnCredentials()
    {
        Directory.CreateDirectory(_tempDir);
        TlbxDirectory.WriteInstanceCliScripts(_tempDir, 2000, "supervisor-token", false);
        var names = new[] { "tlbx_cli.ps1", "tlbx_cli.sh", "tlbx_graphs.ps1", "tlbx_graphs.sh" };
        var originals = names.ToDictionary(name => name, name => File.ReadAllText(Path.Combine(_tempDir, name)), StringComparer.Ordinal);
        TlbxDirectory.WriteInstanceCliScripts(_tempDir, 2100, "source-token", true);
        TlbxDirectory.WriteInstanceCliScripts(_tempDir, 2100, "refreshed-source-token", true);
        foreach (var name in names)
        {
            Assert.Equal(originals[name], File.ReadAllText(Path.Combine(_tempDir, name)));
            var source = File.ReadAllText(Path.Combine(_tempDir, "instances", "2100", name));
            Assert.Contains("2100", source, StringComparison.Ordinal);
            Assert.Contains("refreshed-source-token", source, StringComparison.Ordinal);
            Assert.DoesNotContain("supervisor-token", source, StringComparison.Ordinal);
        }
    }

    [Fact]
    public void WriteScripts_BashBootstrapProducesValidJsonWithSlashCommands()
    {
        var bashPath = ResolveBashPath();
        if (bashPath is null)
        {
            return;
        }

        Directory.CreateDirectory(_tempDir);
        TlbxCliScriptWriter.WriteScripts(_tempDir, 2000, "test-token");

        var scriptPath = ToBashPath(Path.Combine(_tempDir, "tlbx_cli.sh"));
        var startInfo = new ProcessStartInfo(bashPath)
        {
            RedirectStandardOutput = true,
            RedirectStandardError = true,
            UseShellExecute = false
        };
        startInfo.ArgumentList.Add("-c");
        startInfo.ArgumentList.Add(
            "source \"$1\"; _MJ() { printf '%s' \"$2\"; }; " +
            "mt_bootstrap 'review \"worker\"' 'Q:/repo with space' codex status compact");
        startInfo.ArgumentList.Add("midterm-test");
        startInfo.ArgumentList.Add(scriptPath);

        using var process = Process.Start(startInfo)!;
        var output = process.StandardOutput.ReadToEnd();
        var error = process.StandardError.ReadToEnd();
        process.WaitForExit();

        Assert.True(process.ExitCode == 0, error);
        using var json = JsonDocument.Parse(output);
        var root = json.RootElement;
        Assert.Equal("review \"worker\"", root.GetProperty("name").GetString());
        Assert.Equal("Q:/repo with space", root.GetProperty("workingDirectory").GetString());
        Assert.Equal("codex", root.GetProperty("profile").GetString());
        var slashCommands = root.GetProperty("slashCommands");
        Assert.Equal(2, slashCommands.GetArrayLength());
        Assert.Equal("status", slashCommands[0].GetString());
        Assert.Equal("compact", slashCommands[1].GetString());
    }

    [Fact]
    public void WriteScripts_BashRunIsolatedKeepsChildBytesOutOfCallerAndPreservesArgv()
    {
        var bashPath = ResolveBashPath();
        if (bashPath is null)
        {
            return;
        }

        Directory.CreateDirectory(_tempDir);
        TlbxCliScriptWriter.WriteScripts(_tempDir, 2000, "test-token");
        var childPath = Path.Combine(_tempDir, "isolated-child.sh");
        File.WriteAllText(childPath,
            "sleep 0.15\n" +
            "printf 'stdout-sentinel\\n'\n" +
            "printf 'arg1=<%s>\\n' \"$1\"\n" +
            "printf 'arg2=<%s>\\n' \"$2\"\n" +
            "printf 'arg3=<%s>\\n' \"$3\"\n" +
            "if IFS= read -r line; then printf 'stdin=<%s>\\n' \"$line\"; else printf 'stdin=<eof>\\n'; fi\n" +
            "printf 'stderr-sentinel\\n' >&2\n");

        var startInfo = new ProcessStartInfo(bashPath)
        {
            RedirectStandardOutput = true,
            RedirectStandardError = true,
            UseShellExecute = false
        };
        startInfo.ArgumentList.Add("-c");
        startInfo.ArgumentList.Add("source \"$1\"; mt_run_isolated \"$2\" \"$3\" \"$4\" \"$5\" \"$6\"");
        startInfo.ArgumentList.Add("midterm-test");
        startInfo.ArgumentList.Add(ToBashPath(Path.Combine(_tempDir, "tlbx_cli.sh")));
        startInfo.ArgumentList.Add(ToBashPath(bashPath));
        startInfo.ArgumentList.Add(ToBashPath(childPath));
        startInfo.ArgumentList.Add("two words");
        startInfo.ArgumentList.Add("quote\"value");
        startInfo.ArgumentList.Add("slash and space\\");

        using var process = Process.Start(startInfo)!;
        var output = process.StandardOutput.ReadToEnd();
        var error = process.StandardError.ReadToEnd();
        process.WaitForExit();

        Assert.True(process.ExitCode == 0, error);
        Assert.DoesNotContain("stdout-sentinel", output, StringComparison.Ordinal);
        Assert.DoesNotContain("stderr-sentinel", error, StringComparison.Ordinal);
        using var receipt = JsonDocument.Parse(output);
        var root = receipt.RootElement;
        Assert.True(root.GetProperty("pid").GetInt32() > 0);
        var runId = root.GetProperty("runId").GetString()!;
        var stdoutPath = Path.Combine(_tempDir, "runs", runId, "stdout.log");
        var stderrPath = Path.Combine(_tempDir, "runs", runId, "stderr.log");

        var childOutput = WaitForFileContent(stdoutPath, content => content.Contains("stdin=<eof>", StringComparison.Ordinal));
        var childError = WaitForFileContent(stderrPath, content => content.Contains("stderr-sentinel", StringComparison.Ordinal));
        Assert.Contains("stdout-sentinel", childOutput, StringComparison.Ordinal);
        Assert.Contains("arg1=<two words>", childOutput, StringComparison.Ordinal);
        Assert.Contains("arg2=<quote\"value>", childOutput, StringComparison.Ordinal);
        Assert.Contains("arg3=<slash and space\\>", childOutput, StringComparison.Ordinal);
        Assert.Equal("stderr-sentinel", childError.Trim());
        Assert.EndsWith($"/runs/{runId}/stdout.log", root.GetProperty("stdoutPath").GetString()!.Replace('\\', '/'), StringComparison.Ordinal);
        Assert.EndsWith($"/runs/{runId}/stderr.log", root.GetProperty("stderrPath").GetString()!.Replace('\\', '/'), StringComparison.Ordinal);
    }

    [Fact]
    public void WriteScripts_PowerShellRunIsolatedKeepsChildBytesOutOfCallerAndPreservesArgv()
    {
        var powershellPath = ResolvePowerShellPath();
        if (powershellPath is null)
        {
            return;
        }

        Directory.CreateDirectory(_tempDir);
        TlbxCliScriptWriter.WriteScripts(_tempDir, 2000, "test-token");
        var childPath = Path.Combine(_tempDir, "isolated-child.ps1");
        File.WriteAllText(childPath,
            "param([Parameter(ValueFromRemainingArguments=$true)][string[]]$InputArgs)\n" +
            "Start-Sleep -Milliseconds 150\n" +
            "[Console]::Out.WriteLine('stdout-sentinel')\n" +
            "$InputArgs | ForEach-Object -Begin { $index = 0 } -Process { [Console]::Out.WriteLine(('arg{0}=<{1}>' -f (++$index), $_)) }\n" +
            "[Console]::Out.WriteLine(('stdin-length={0}' -f ([Console]::In.ReadToEnd().Length)))\n" +
            "[Console]::Error.WriteLine('stderr-sentinel')\n");

        var startInfo = new ProcessStartInfo(powershellPath)
        {
            RedirectStandardOutput = true,
            RedirectStandardError = true,
            UseShellExecute = false
        };
        startInfo.ArgumentList.Add("-NoProfile");
        startInfo.ArgumentList.Add("-File");
        startInfo.ArgumentList.Add(Path.Combine(_tempDir, "tlbx_cli.ps1"));
        startInfo.ArgumentList.Add("mt_run_isolated");
        startInfo.ArgumentList.Add(powershellPath);
        startInfo.ArgumentList.Add("-NoProfile");
        startInfo.ArgumentList.Add("-NonInteractive");
        startInfo.ArgumentList.Add("-File");
        startInfo.ArgumentList.Add(childPath);
        startInfo.ArgumentList.Add("two words");
        startInfo.ArgumentList.Add("quote\"value");
        startInfo.ArgumentList.Add("slash and space\\");

        using var process = Process.Start(startInfo)!;
        var output = process.StandardOutput.ReadToEnd();
        var error = process.StandardError.ReadToEnd();
        process.WaitForExit();

        Assert.True(process.ExitCode == 0, error);
        Assert.DoesNotContain("stdout-sentinel", output, StringComparison.Ordinal);
        Assert.DoesNotContain("stderr-sentinel", error, StringComparison.Ordinal);
        using var receipt = JsonDocument.Parse(output);
        var root = receipt.RootElement;
        Assert.True(root.GetProperty("pid").GetInt32() > 0);
        var runId = root.GetProperty("runId").GetString()!;
        var stdoutPath = root.GetProperty("stdoutPath").GetString()!;
        var stderrPath = root.GetProperty("stderrPath").GetString()!;
        Assert.Equal(Path.Combine(_tempDir, "runs", runId, "stdout.log"), stdoutPath);
        Assert.Equal(Path.Combine(_tempDir, "runs", runId, "stderr.log"), stderrPath);

        var childOutput = WaitForFileContent(stdoutPath, content => content.Contains("stdin-length=0", StringComparison.Ordinal));
        var childError = WaitForFileContent(stderrPath, content => content.Contains("stderr-sentinel", StringComparison.Ordinal));
        Assert.Contains("stdout-sentinel", childOutput, StringComparison.Ordinal);
        Assert.Contains("arg1=<two words>", childOutput, StringComparison.Ordinal);
        Assert.Contains("arg2=<quote\"value>", childOutput, StringComparison.Ordinal);
        Assert.Contains("arg3=<slash and space\\>", childOutput, StringComparison.Ordinal);
        Assert.Equal("stderr-sentinel", childError.Trim());
    }

    [Fact]
    public void WriteScripts_PowerShellRunIsolated_RemovesExpiredCompletedRuns()
    {
        var powershellPath = ResolvePowerShellPath();
        if (powershellPath is null)
        {
            return;
        }

        Directory.CreateDirectory(_tempDir);
        TlbxCliScriptWriter.WriteScripts(_tempDir, 2000, "test-token");
        var expiredRun = Path.Combine(_tempDir, "runs", "expired-run");
        Directory.CreateDirectory(expiredRun);
        Directory.SetLastWriteTimeUtc(expiredRun, DateTime.UtcNow.AddDays(-15));

        var startInfo = new ProcessStartInfo(powershellPath)
        {
            RedirectStandardOutput = true,
            RedirectStandardError = true,
            UseShellExecute = false
        };
        startInfo.ArgumentList.Add("-NoProfile");
        startInfo.ArgumentList.Add("-File");
        startInfo.ArgumentList.Add(Path.Combine(_tempDir, "tlbx_cli.ps1"));
        startInfo.ArgumentList.Add("mt_run_isolated");
        startInfo.ArgumentList.Add(powershellPath);
        startInfo.ArgumentList.Add("-NoProfile");
        startInfo.ArgumentList.Add("-Command");
        startInfo.ArgumentList.Add("exit 0");

        using var process = Process.Start(startInfo)!;
        var output = process.StandardOutput.ReadToEnd();
        var error = process.StandardError.ReadToEnd();
        process.WaitForExit();

        Assert.True(process.ExitCode == 0, error + output);
        Assert.False(Directory.Exists(expiredRun));

        var shell = File.ReadAllText(Path.Combine(_tempDir, "tlbx_cli.sh"));
        var powershell = File.ReadAllText(Path.Combine(_tempDir, "tlbx_cli.ps1"));
        Assert.Contains("max_completed_runs=100", shell, StringComparison.Ordinal);
        Assert.Contains("max_completed_kib=1048576", shell, StringComparison.Ordinal);
        Assert.Contains("$maxCompletedRuns = 100", powershell, StringComparison.Ordinal);
        Assert.Contains("$maxCompletedBytes = 1GB", powershell, StringComparison.Ordinal);
    }

    public void Dispose()
    {
        try
        {
            if (Directory.Exists(_tempDir))
            {
                Directory.Delete(_tempDir, recursive: true);
            }
        }
        catch
        {
        }
    }

    private static string? ResolveBashPath()
    {
        string[] candidates = OperatingSystem.IsWindows()
            ? [@"C:\Program Files\Git\bin\bash.exe", @"C:\Program Files\Git\usr\bin\bash.exe"]
            : ["/bin/bash", "/usr/bin/bash"];

        return candidates.FirstOrDefault(File.Exists);
    }

    private static string? ResolvePowerShellPath()
    {
        string[] candidates = OperatingSystem.IsWindows()
            ? [@"C:\Program Files\PowerShell\7\pwsh.exe"]
            : ["/usr/bin/pwsh", "/usr/local/bin/pwsh"];

        var fixedPath = candidates.FirstOrDefault(File.Exists);
        if (fixedPath is not null)
        {
            return fixedPath;
        }

        var executableName = OperatingSystem.IsWindows() ? "pwsh.exe" : "pwsh";
        return (Environment.GetEnvironmentVariable("PATH") ?? string.Empty)
            .Split(Path.PathSeparator, StringSplitOptions.RemoveEmptyEntries)
            .Select(path => Path.Combine(path, executableName))
            .FirstOrDefault(File.Exists);
    }

    private static string WaitForFileContent(string path, Func<string, bool> completed)
    {
        var timeout = Stopwatch.StartNew();
        string content = string.Empty;
        while (timeout.Elapsed < TimeSpan.FromSeconds(10))
        {
            if (File.Exists(path))
            {
                try
                {
                    content = File.ReadAllText(path);
                    if (completed(content))
                    {
                        return content;
                    }
                }
                catch (IOException)
                {
                }
            }

            Thread.Sleep(25);
        }

        Assert.Fail($"Timed out waiting for isolated run artifact '{path}'. Last content: {content}");
        return content;
    }

    private static string ToBashPath(string path)
    {
        if (!OperatingSystem.IsWindows())
        {
            return path;
        }

        var normalized = path.Replace('\\', '/');
        return normalized.Length >= 3 && normalized[1] == ':'
            ? $"/{char.ToLowerInvariant(normalized[0])}/{normalized[3..]}"
            : normalized;
    }
}
