export const COLLAPSIBLE_HISTORY_BODY_MIN_LINES = 8;
export const COLLAPSIBLE_HISTORY_BODY_MIN_CHARS = 320;
export const COLLAPSIBLE_HISTORY_BODY_PREVIEW_CHARS = 160;
export const MAX_VISIBLE_DIFF_LINES = 200;
export const DEFAULT_TOOL_CALL_OUTPUT_LINES = 5;
export const MAX_TOOL_CALL_OUTPUT_LINES = 20;
